// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace E_CommerceWebAPI.Models;

public partial class commerce_dbContext : DbContext
{
    public commerce_dbContext(DbContextOptions<commerce_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderProduct> OrderProducts { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductShopping> ProductShoppings { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }

    public virtual DbSet<StatusOrder> StatusOrders { get; set; }

    public virtual DbSet<StatusPayment> StatusPayments { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.IdOrder).HasName("pk_order");

            entity.Property(e => e.IdOrder).HasColumnName("id_order");
            entity.Property(e => e.DateOrder)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("date_order");
            entity.Property(e => e.IdStatus).HasColumnName("id_status");
            entity.Property(e => e.IdUser).HasColumnName("id_user");

            entity.HasOne(d => d.IdStatusNavigation).WithMany(p => p.Orders)
                .HasForeignKey(d => d.IdStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_order_status");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.Orders)
                .HasForeignKey(d => d.IdUser)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user");
        });

        modelBuilder.Entity<OrderProduct>(entity =>
        {
            entity.HasKey(e => new { e.IdProd, e.IdOrder }).HasName("pk_product_order");

            entity.ToTable("Order_Products");

            entity.Property(e => e.IdProd).HasColumnName("id_prod");
            entity.Property(e => e.IdOrder).HasColumnName("id_order");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.IdOrderNavigation).WithMany(p => p.OrderProducts)
                .HasForeignKey(d => d.IdOrder)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_order_product");

            entity.HasOne(d => d.IdProdNavigation).WithMany(p => p.OrderProducts)
                .HasForeignKey(d => d.IdProd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_product");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.IdPay).HasName("pk_payment");

            entity.Property(e => e.IdPay).HasColumnName("id_pay");
            entity.Property(e => e.AmountPay)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("amount_pay");
            entity.Property(e => e.DatePay)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("date_pay");
            entity.Property(e => e.IdMethod).HasColumnName("id_method");
            entity.Property(e => e.IdOrder).HasColumnName("id_order");
            entity.Property(e => e.IdStatus).HasColumnName("id_status");
            entity.Property(e => e.StripeId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("stripe_id");

            entity.HasOne(d => d.IdMethodNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.IdMethod)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_method");

            entity.HasOne(d => d.IdOrderNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.IdOrder)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_order");

            entity.HasOne(d => d.IdStatusNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.IdStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_payment_status");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.IdMethod).HasName("pk_method");

            entity.ToTable("Payment_Methods");

            entity.Property(e => e.IdMethod).HasColumnName("id_method");
            entity.Property(e => e.NameMethod)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name_method");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.IdProd).HasName("pk_product");

            entity.Property(e => e.IdProd).HasColumnName("id_prod");
            entity.Property(e => e.Active)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("Y")
                .IsFixedLength()
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_active")
                .HasColumnName("active");
            entity.Property(e => e.DescrProd)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("descr_prod");
            entity.Property(e => e.NameProd)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("name_prod");
            entity.Property(e => e.PriceProd)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("price_prod");
            entity.Property(e => e.StockProd).HasColumnName("stock_prod");
        });

        modelBuilder.Entity<ProductShopping>(entity =>
        {
            entity.HasKey(e => new { e.IdProd, e.IdCart }).HasName("pk_product_shoppings");

            entity.ToTable("Product_Shoppings");

            entity.Property(e => e.IdProd).HasColumnName("id_prod");
            entity.Property(e => e.IdCart).HasColumnName("id_cart");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.IdCartNavigation).WithMany(p => p.ProductShoppings)
                .HasForeignKey(d => d.IdCart)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_cart");

            entity.HasOne(d => d.IdProdNavigation).WithMany(p => p.ProductShoppings)
                .HasForeignKey(d => d.IdProd)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_product_cart");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.IdRol).HasName("pk_roles");

            entity.Property(e => e.IdRol).HasColumnName("idRol");
            entity.Property(e => e.NameRol)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nameRol");
        });

        modelBuilder.Entity<ShoppingCart>(entity =>
        {
            entity.HasKey(e => e.IdCart).HasName("pk_cart");

            entity.ToTable("Shopping_Carts");

            entity.Property(e => e.IdCart).HasColumnName("id_cart");
            entity.Property(e => e.IdUser).HasColumnName("id_user");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.ShoppingCarts)
                .HasForeignKey(d => d.IdUser)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_cart");
        });

        modelBuilder.Entity<StatusOrder>(entity =>
        {
            entity.HasKey(e => e.IdStOrder).HasName("pk_st_order");

            entity.ToTable("Status_Orders");

            entity.Property(e => e.IdStOrder).HasColumnName("id_st_order");
            entity.Property(e => e.NameStOrder)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name_st_order");
        });

        modelBuilder.Entity<StatusPayment>(entity =>
        {
            entity.HasKey(e => e.IdStPay).HasName("pk_st_payment");

            entity.ToTable("Status_Payments");

            entity.Property(e => e.IdStPay).HasColumnName("id_st_pay");
            entity.Property(e => e.NameStPay)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name_st_pay");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.IdUser).HasName("pk_user");

            entity.Property(e => e.IdUser).HasColumnName("id_user");
            entity.Property(e => e.IdRol).HasColumnName("idRol");
            entity.Property(e => e.NameUser)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name_user");
            entity.Property(e => e.PassUser)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("pass_user");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_roles_user");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}