// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class OrderProduct
{
    public int IdProd { get; set; }

    public int IdOrder { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public virtual Order IdOrderNavigation { get; set; }

    public virtual Product IdProdNavigation { get; set; }
}