// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class Payment
{
    public int IdPay { get; set; }

    public int IdOrder { get; set; }

    public DateTime DatePay { get; set; }

    public decimal AmountPay { get; set; }

    public int IdMethod { get; set; }

    public int IdStatus { get; set; }

    public string StripeId { get; set; }

    public virtual PaymentMethod IdMethodNavigation { get; set; }

    public virtual Order IdOrderNavigation { get; set; }

    public virtual StatusPayment IdStatusNavigation { get; set; }
}