// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class ProductShopping
{
    public int IdProd { get; set; }

    public int IdCart { get; set; }

    public int Quantity { get; set; }

    public virtual ShoppingCart IdCartNavigation { get; set; }

    public virtual Product IdProdNavigation { get; set; }
}