// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class Product
{
    public int IdProd { get; set; }

    public string NameProd { get; set; }

    public string DescrProd { get; set; }

    public decimal PriceProd { get; set; }

    public int StockProd { get; set; }

    public string Active { get; set; }

    public virtual ICollection<OrderProduct> OrderProducts { get; set; } = new List<OrderProduct>();

    public virtual ICollection<ProductShopping> ProductShoppings { get; set; } = new List<ProductShopping>();
}