// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class Role
{
    public int IdRol { get; set; }

    public string NameRol { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}