// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class ShoppingCart
{
    public int IdCart { get; set; }

    public int IdUser { get; set; }

    public virtual User IdUserNavigation { get; set; }

    public virtual ICollection<ProductShopping> ProductShoppings { get; set; } = new List<ProductShopping>();
}