// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class StatusPayment
{
    public int IdStPay { get; set; }

    public string NameStPay { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}