// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class StatusOrder
{
    public int IdStOrder { get; set; }

    public string NameStOrder { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}