// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceWebAPI.Models;

public partial class User
{
    public int IdUser { get; set; }

    public string NameUser { get; set; }

    public string PassUser { get; set; }

    public int IdRol { get; set; }

    public virtual Role IdRolNavigation { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; } = new List<ShoppingCart>();
}